-- local server_config = require('lspconfig.configs')
-- local root_pattern = require('lspconfig.util').root_pattern
--
-- server_config.raku = {
--     default_config = {
--     cmd = {'/Users/wsun/projects/raku_nvim/old_fold/lsp/t/lsp.raku', '--vim'},
--         name = 'raku',
--         filetypes = {
--             'raku',
--             'rakumod',
--             'rakutest',
--             'perl6'
--         },
--         root_dir = root_pattern('', 'package.json', 'META6.json')
--     }
-- }
--
-- require('lspconfig').raku.setup({})
